services:
  - type: web
    name: manaah-platform
    env: node
    plan: free
    buildCommand: ./scripts/render-build.sh
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: manaah-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: manaah-platform
          property: host
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: manaah-platform
          property: host
      - key: WOAH_API_URL
        value: https://wahis.woah.org/api
      - key: MONITORING_ENABLED
        value: true
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: manaah-platform
          property: host

databases:
  - name: manaah-db
    databaseName: manaah_platform
    user: manaah_user
    plan: free