# Render Blueprint for Manaah Platform MCP Server
services:
  # MCP Server Web Service
  - type: web
    name: manaah-mcp-server
    runtime: docker
    plan: starter # Free tier
    region: oregon # Choose your preferred region
    branch: main # or your default branch
    dockerfilePath: ./mcp-server/Dockerfile
    dockerContext: ./mcp-server
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: MCP_SERVER_NAME
        value: Manaah Platform MCP Server
      - key: MCP_SERVER_VERSION
        value: "1.0.0"
      - key: API_BASE_URL
        value: https://manaah-mcp-server.onrender.com
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: manaah-mcp-server
          property: url
      
      # Database connection (will be set from database service)
      - key: DATABASE_URL
        fromDatabase:
          name: manaah-postgres
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: manaah-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: manaah-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: manaah-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: manaah-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: manaah-postgres
          property: password
      
      # JWT Secret (generate a secure random string)
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "24h"
    
    # Health check endpoint
    healthCheckPath: /health
    
    # Auto-deploy on git push
    autoDeploy: true

  # PostgreSQL Database
  - type: pserv
    name: manaah-postgres
    runtime: postgresql
    plan: starter # Free tier (expires after 90 days)
    region: oregon # Same region as web service
    
    # Database configuration
    databaseName: manaah_platform
    databaseUser: manaah_user
    
    # PostGIS extension for geographic data
    postgresMajorVersion: 15
    
    # Backup configuration
    ipAllowList: [] # Empty means allow all IPs

# Optional: Redis for caching (if needed later)
# - type: redis
#   name: manaah-redis
#   plan: starter
#   region: oregon
#   maxmemoryPolicy: allkeys-lru